GARNAME = autoconf
GARVERSION = 2.61
MASTER_SITES = http://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = $(WORKSRC)/doc/autoconf.texi
NODIST_BOOKS = $(WORKSRC)/doc/standards.texi

include ../../gar.mk

