GARNAME = texinfo
GARVERSION = 4.8a
MASTER_SITES = http://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

WORKSRC = $(WORKDIR)/$(GARNAME)-4.8

BOOKS = \
	$(WORKSRC)/doc/texinfo.txi \
	$(WORKSRC)/doc/info.texi

include ../../gar.mk
