GARNAME = tex-refs
GARVERSION = 0.3.9
MASTER_SITES = http://www.miwie.org/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = $(WORKSRC)/tex-refs.xml

BUILD_SCRIPTS = $(WORKSRC)/Makefile
BUILD_ARGS = tex-refs.xml

include ../../gar.mk
