GARNAME = cvs
GARVERSION = 1.11.22
MASTER_SITES = http://ftp.gnu.org/pub/non-gnu/$(GARNAME)/source/stable/$(GARVERSION)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = $(WORKSRC)/doc/cvs.texinfo

include ../../gar.mk

