GARNAME = bc
GARVERSION = 1.06
MASTER_SITES = http://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

BOOKS = \
	$(WORKSRC)/doc/bc.texi \
	$(WORKSRC)/doc/dc.texi

include ../../gar.mk
