GARNAME = gawk
GARVERSION = 3.1.6
MASTER_SITES = http://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = \
	$(WORKSRC)/doc/gawk.texi \
	$(WORKSRC)/doc/gawkinet.texi

include ../../gar.mk

