GARNAME = readline
GARVERSION = 5.2
MASTER_SITES = http://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

BOOKS = \
	$(WORKSRC)/doc/rlman.texi \
	$(WORKSRC)/doc/rluserman.texi \
	$(WORKSRC)/doc/history.texi

include ../../gar.mk
